### PR TITLE
Updated all Design systems, and removed index formula circle

### PR DESCRIPTION
**Pull request by Rnhatch**
All design systems in sample pages updated after last production change. 

The fix to index formula field was in other sample pages besides mobile list.  Removed the field from those pages.  No impact to page performance.

### CODE REVIEW

**Comment by Rnhatch** [comment]
@hyork  - Cody can't review this Sample Pages repo change.   Could you do this for me?   Thanks.

**Comment by hyork** [comment]
Thanks so much for this update @Rnhatch. Everything's checking out, except 2 small issues on the Compact Workspace and Material design systems per screenshots below. Re-saving seems to fix it. Idk if that's something that will always require users to re-save even if you upload another round of freshly saved DS. If you want to upload another round, I can test again. 

_Tab Sets not looking right on Material_
Screen Shot 2020-10-08 at 4 42 46 PM
_Accordion styling not applied on Compact Workspace_
Screen Shot 2020-10-08 at 4 37 47 PM

**Comment by Rnhatch** [comment]
@hyork  Sorry I didn't get to this in the week.  But I revised and resaved the two DS in question.  Should be an easy review for your Monday morning.

**Review by hyork — APPROVED** [review]
Thanks Rob! Looks good!

**Pull request merged**
